[project]
name = "mgc-token-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pyright>=1.1.400",
    "ruff>=0.11.7",
    "twine>=6.1.0",
]
